# secrets.toml

[snowflake]
user = "johanstreamlit"
password = "Rbbpr66#C$7x3i&8N"
account = "qrvjfqx-kl85917"
warehouse = "COMPUTE_WH"
database = "PETS"
schema = "PUBLIC"
AWS_ACCESS_KEY_ID="ASIARDYMKQYWHKFR3KOW"
AWS_SECRET_ACCESS_KEY="FRz6/kE+MjKObG1tP6w92SKeRsnbB+6huOTT+VBg"
AWS_SESSION_TOKEN="IQoJb3JpZ2luX2VjEJf//////////wEaCWV1LXdlc3QtMSJGMEQCIDtN1K2s4DGDR8KEtbpeRibuMn/ymSHpl6DmYra55ldKAiBvYsJRy2kjGJkey0U2nxxncGhLT7aShCNB7/U66V/4kyqhAwhwEAIaDDA3Njc5ODM5NTk0OCIM/fEdopTg902jbnBzKv4Ci2LYEpOiXS/a2ry2t1mGwRyPydbsc1rhJqU5ljyt7pRLtqHpj0+fgPg6U9gZTcSHmqXktxVgSb366HN5A8UScPwkBntQSERMNtXopFzyJ2jXhKuaezF3x83LRIR1xTYgM9cIm6n8hUutvjDhgwixALE1tCrrJuZlfONdpLyGmmdwTcCL+IH+A7zwAojNT8WZGwkt/hzPlKxRyHDnjSyoWaCQg9OUtd1Ci+UgMXUwPLBnZh8RsBPq8NKGjFVQshZ7gIIujjW2Fa6xYg3TYqXoAP7sT5OifuyDf8r8ApL5Rc9zDDvJWXwHT/+8rfxlTwjQAe0IPHbJukQ/YYLzOP2tSGW5HbI8kegVJuUBUL7NUbVRgJ+1S+yjjnfGFyqAptQPrt6qX1/Sxk8rXjJyVyn6V52VkkJxr97S3FNtp1rhuvS1iyg1qnMYP+cjS5287VgrUoM5EKjhrc1/E/PtNxqr/sFqNEuFPhDAsB/D44+sADKoAX8df0CCowqj44iXfDCk5pShBjqnATrs5sn9ylxQlCB79s37i3WCEaQPYvoSyxT3eYGzV5sZn++pdudLX4hPYl0BgDO7Zt39f72jzivAtY+hEyH+u8Zdhourth0KHS3Wu3XCOQ+EPDCOkpGWtnwBXfn/5pqfb2heCew86ZBP0g7pBCrFMie7ri9Gso2M3thUmLmCeyaZENZsNtH79AVlMbo1lcHUJkctb+exLGr3vrCv/u3U83FTm6Xbr0N0"