# secrets.toml

[snowflake]
user = "johanstreamlit"
password = "Rbbpr66#C$7x3i&8N"
account = "qrvjfqx-kl85917"
warehouse = "COMPUTE_WH"
database = "PETS"
schema = "PUBLIC"
AWS_ACCESS_KEY_ID="ASIARDYMKQYWFLPMW4GI"
AWS_SECRET_ACCESS_KEY="988A8M/n3Y8fnvgFxh5PwKAGkSW54JoIKUpf1bAi"
AWS_SESSION_TOKEN="IQoJb3JpZ2luX2VjEJf//////////wEaCWV1LXdlc3QtMSJGMEQCIC9VpJ+iMtAXRGd76VVtkMEJ4cxci3shK1cTZQ8JtQ9zAiAxNUViCgHIb13b+6/WNhUrhgrnQ9xWycRkescbswbTBCqhAwhwEAIaDDA3Njc5ODM5NTk0OCIMP2ofQ8RfGH4bpy7vKv4CQUnuM4MvIIwpZ2QOm2mcp4xVnyk0+LG34t+dnpvK5pc2F9CZfj2LMVduNPtd3Cz1uDCUx6KpQDReVoSU53eqN6JDwYtX/2kOKbdT5rK35kVfAYNFfBPkLmXl22z81emS355X/0CmnHPhpWt3RVE/6IM3m9vwICSlpb63BJeHQRqehJY56lMhXl5cU58Uxh9dJ+bImDjElWq1HzHwqdSCkPb/1hQs11ddkHhzEGIA+fTjDYpk7cPOdK6HAPLtdDS1jfx3ow8NIcD8F33Ue3Ew7qgAl0JiRe5gPqNxubKEn9VSZlMDI7jL2Mxs9otnWsFAGmB8EgeyyXO3+xYUG8LuhRCiIsMViZJbWw8h5tFdOwYQgWk9hLG8v1Sw7ApyVZESpzkzC9M9jBfvVDcfYjQK/nxHJtDXg/wSxJ91rFyPIDc8m58mPeLFxZwrc914jTcC4FsXJRWXAkK6oZydS+UGXQq2ZMFREo8Cuqswn0TR8ZjkZ4odu4ZDOOAR2AhveDDb3ZShBjqnAZy3jw2aHWsLXv/Tr/fMT/dkUe2Rhwoj+wSAxcGVPk9qfUiffcrujReLQXZ/i3/Bdqwgqm0Dn/TxLorOK6fEQkKdtXg5XpPJ6OJYqOv10qH8DtsL7zSEZy3SNli59U5rWdxzVExwgXZ9ZN0Cqqr16vjPLA0eso+tdmcGx1qbymD4i+4lwQDdpWCeXp+YA/BgkV/vSTPmuVEYcls3sarsAEvsGnKv930U"